version: "3.9"

services:

  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=cityservice
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      DATABASE_URL: postgresql://user:pass@db/cityservice
    depends_on:
      - db
