"""empty message

Revision ID: 6d5dc21ec10c
Revises:
Create Date: 2020-03-20 11:32:33.349715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d5dc21ec10c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsitems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("publisher_name", sa.String(), nullable=True),
        sa.Column("publisher_icon_url", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("link_url", sa.String(), nullable=True),
        sa.Column("published", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("newsitems")
    # ### end Alembic commands ###
