"""empty message

Revision ID: af5ea35acbbb
Revises: 62f7eba939be
Create Date: 2020-09-05 14:11:02.786547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5ea35acbbb'
down_revision = '62f7eba939be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recyclingstreets', sa.Column('town_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recyclingstreets', 'town_id')
    # ### end Alembic commands ###
