default_platform(:android)

GITHUB_RUN_NUMBER = ENV["GITHUB_RUN_NUMBER"]

platform :android do

  desc "Increment version code"
  lane :increment_vc do
    android_set_version_code(
      version_code: GITHUB_RUN_NUMBER,
      gradle_file: "app/build.gradle",
    )
  end

  desc "Build release bundle"
  lane :build do
    gradle(task: "clean bundleRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_vc
    build
    upload_to_play_store(
      track: "internal",
      release_status: "draft"
    )
  end
end
