default_platform(:android)

platform :android do

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
    )
  end

  desc "Build release bundle"
  lane :build do
    gradle(task: "clean bundleRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_vc
    build
    upload_to_play_store(
      track: "internal",
      release_status: "draft"
    )
  end
end
