name: Lint

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-lateststeps:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npm build